server {
    listen 80;
    server_name _;

    location / {
        if ($geoip2_data_country_code = "RU") {
            return 403;
        }
        
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Перехватываем ошибку 403
    error_page 403 /blocked.html;
    
    location /blocked.html {
        root /usr/share/nginx/html;
        internal;
    }
}